development:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['D_DB'] %>
  pool: 5
  username: <%= ENV['D_DB_USER'] %>
  password: <%= ENV['D_DB_PASS'] %>
  host: <%= ENV['D_DB_HOST'] %>
  port: <%= ENV['D_DB_PORT'] %>

test:
  adapter: postgresql
  encoding: unicode
  database: orcamento_test
  pool: 5
  username: blenno
  password: 123456
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['P_DB'] %>
  pool: 5
  username: <%= ENV['P_DB_USER'] %>
  password: <%= ENV['P_DB_PASS'] %>
  host: <%= ENV['P_DB_HOST'] %>
  port: <%= ENV['P_DB_PORT'] %>